version: '3'
services:
  nginx:
    image: nginx:1.15.2-alpine-perl
    build: ./docker/nginx/
    ports:
      - "1443:1443"
    depends_on:
      - php
    volumes:
      - ./cert:/usr/local/nginx/conf
      - ./html:/var/www/html
      - ./conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/fcgi_params:/etc/nginx/fcgi_params
      - ./log:/var/log/nginx
      # - ./conf/nginx/.htpasswd:/etc/nginx/.htpasswd
    networks:
      - backend

  php:
    build: ./docker/php/
    volumes:
      - ./html:/var/www/html
    tty: true
    networks:
      - backend
      - untrust

  secret_web:
    image: nginx
    volumes:
      - ./cert:/usr/local/nginx/conf
      - ./conf/secret_web/site.conf:/etc/nginx/conf.d/default.conf
      - ./secret_html:/var/www/secret_html
    networks:
      - backend
  
  attacker_server:
    image: python:3-alpine
    volumes: 
      - ./app.py:/code/app.py
    ports:
      - 8888:8888
    networks:
      - untrust
    command: python /code/app.py
    
networks:
  backend:
    ipam:
      config:
        - subnet: 1.1.1.0/29
  untrust:
    ipam:
      config:
        - subnet: 2.2.2.0/29